In [1]:
# Importando bibliotecas
import pandas as  pd 
import matplotlib.pyplot as plt
import plotly.express as px
import statsmodels.api as sm

In [2]:

dados = pd.read_csv('clientes_restaurantes.csv')
dados.head()

       data  Chimi & Churri  Assa Frão
0  1/1/2016            65.0      139.0
1  1/2/2016            24.0       85.0
2  1/3/2016            24.0       81.0
3  1/4/2016            23.0       32.0
4  1/5/2016             2.0       43.0

In [3]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 478 entries, 0 to 477
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   data            478 non-null    object
 1   Chimi & Churri  476 non-null    float64
 2   Assa Frão       477 non-null    float64
dtypes: float64(2), object(1)
memory usage: 11.3+ KB

In [4]:

# transformação de colunas de data para datetime
dados['data'] = pd.to_datetime(dados['data'])
dados.set_index('data', inplace=True)

In [5]:
dados

            Chimi & Churri  Assa Frão
data
2016-01-01            65.0      139.0
2016-01-02            24.0       85.0
2016-01-03            24.0       81.0
2016-01-04            23.0       32.0
2016-01-05             2.0       43.0
...                    ...        ...
2017-04-18            30.0       18.0
2017-04-19            20.0       18.0
2017-04-20            22.0       46.0
2017-04-21            38.0       38.0
2017-04-22            97.0       59.0

[478 rows x 2 columns]